//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZininaSesssia2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discipline
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Discipline()
        {
            this.DisciplineDepartments = new HashSet<DisciplineDepartment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Semester { get; set; }
        public int IdSpeciality { get; set; }
        public int LectureHours { get; set; }
        public int LabHours { get; set; }
        public int PracticeHours { get; set; }
        public int CourseProjectHours { get; set; }
        public int IdReportType { get; set; }
    
        public virtual ReportType ReportType { get; set; }
        public virtual Specialite Specialite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisciplineDepartment> DisciplineDepartments { get; set; }
    }
}
