//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZininaSesssia2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisciplineDepartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DisciplineDepartment()
        {
            this.Activities = new HashSet<Activity>();
        }
    
        public int Id { get; set; }
        public int IdDiscipline { get; set; }
        public int IdDepartment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual Department Department { get; set; }
        public virtual Discipline Discipline { get; set; }
    }
}
