//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZininaSesssia2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Specialite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Specialite()
        {
            this.Disciplines = new HashSet<Discipline>();
        }
    
        public int Id { get; set; }
        public int Code { get; set; }
        public string Name { get; set; }
        public string Qualification { get; set; }
        public int Duration { get; set; }
        public int IdFormOfStory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discipline> Disciplines { get; set; }
        public virtual FormOfStory FormOfStory { get; set; }
    }
}
